/* 
  48
*/
CREATE VIEW V_CATERER 
  (ID_CATERER, CATERER_NAME, CONTACT_NAME, CONTACT_SURNAME)
AS
  SELECT T_CATERER.ID_CATERER, T_CATERER.NAME, T_CONTACT.NAME, T_CONTACT.SURNAME
    FROM T_CATERER JOIN T_CONTACT
    ON T_CATERER.ID_CATERER = T_CONTACT.ID_CATERER;

SELECT * FROM V_CATERER;

INSERT INTO V_CATERER 
  (ID_CATERER, CATERER_NAME, CONTACT_NAME, CONTACT_SURNAME)
  VALUES
  (4, 'Apple', 'Tim', 'Cook');

UPDATE V_CATERER
  SET CONTACT_SURNAME = 'Alex'
    WHERE ID_CATERER = 1;

DELETE FROM V_CATERER
  WHERE ID_CATERER = 3;

/* 
  49
*/
CREATE OR REPLACE VIEW V_SURPLUS
  (MATERIAL, STORE, VOLUME)
AS
  SELECT T_MATERIAL.NAME, T_STORE.NAME, SUM(T_SURPLUS.VOLUME)
    FROM T_MATERIAL JOIN T_SURPLUS  
      ON T_MATERIAL.ID_MATERIAL = T_SURPLUS.ID_MATERIAL
    JOIN T_STORE 
      ON T_SURPLUS.ID_STORE = T_STORE.ID_STORE
  GROUP BY T_MATERIAL.NAME, T_STORE.NAME;

/* 
  50
*/
CREATE VIEW V_SUPPLY
  (CATERER_NAME, MATERIAL, MESSURE, SUPPLY_DATE, PRICE, VOLUME, SUMM)
AS
  SELECT T_CATERER.NAME, T_MATERIAL.NAME, T_MESSURE.NAME, 
         T_SUPPLY.SUPPLY_DATE, T_INPRICE.PRICE,
         T_SUPPLY.VOLUME, T_SUPPLY.VOLUME * T_INPRICE.PRICE
  FROM T_SUPPLY JOIN T_CATERER 
    ON T_SUPPLY.ID_CATERER = T_CATERER.ID_CATERER
  JOIN T_MATERIAL 
    ON T_SUPPLY.ID_MATERIAL = T_MATERIAL.ID_MATERIAL
  JOIN T_MESSURE 
    ON T_MATERIAL.ID_MESSURE = T_MESSURE.ID_MESSURE
  JOIN T_INPRICE 
    ON T_MATERIAL.ID_MATERIAL = T_INPRICE.ID_MATERIAL;

/* 
  51
*/
CREATE VIEW V_STORE
  (STORE, MATERIAL, MESSURE, SUMM)
AS
  SELECT T_STORE.NAME, T_MATERIAL.NAME, T_MESSURE.NAME,
         SUM(T_DELIVER.VOLUME)
    FROM T_DELIVER JOIN T_STORE 
      ON T_DELIVER.ID_STORE = T_STORE.ID_STORE    
    JOIN T_MATERIAL 
      ON T_DELIVER.ID_MATERIAL = T_MATERIAL.ID_MATERIAL
    JOIN T_MESSURE 
      ON T_MATERIAL.ID_MESSURE = T_MESSURE.ID_MESSURE
    WHERE DELIVER_DATE >= '01.01.2017' AND DELIVER_DATE <= '31.12.2017'
  GROUP BY T_STORE.NAME, T_MATERIAL.NAME, T_MESSURE.NAME;

/* 
  52
*/
CREATE VIEW V_SUPPLY_2
  (ID, MATERIAL, VOLUME, STORE, PRICE, SUMM)
AS
  SELECT T_SUPPLY.ID_SUPPLY, T_MATERIAL.NAME, T_SUPPLY.VOLUME, T_STORE.NAME, T_SUPPLY.PRICE, T_SUPPLY.VOLUME * T_SUPPLY.PRICE
    FROM T_SUPPLY JOIN T_MATERIAL 
    ON T_SUPPLY.ID_MATERIAL = T_MATERIAL.ID_MATERIAL
    JOIN T_STORE 
    ON T_SUPPLY.ID_STORE = T_STORE.ID_STORE

CREATE VIEW V_INPRICE
  (ID, MATERIAL, VOLUME, STORE, PRICE, SUMM)
AS
  SELECT T_SUPPLY.ID_SUPPLY, T_MATERIAL.NAME, T_SUPPLY.VOLUME, T_STORE.NAME, T_INPRICE.PRICE, T_SUPPLY.VOLUME * T_INPRICE.PRICE
    FROM T_SUPPLY JOIN T_MATERIAL 
    ON T_SUPPLY.ID_MATERIAL = T_MATERIAL.ID_MATERIAL
    JOIN T_STORE 
    ON T_SUPPLY.ID_STORE = T_STORE.ID_STORE
    JOIN T_INPRICE 
    ON T_MATERIAL.ID_MATERIAL = T_INPRICE.ID_MATERIAL

CREATE VIEW V_COMPARE
  (MATERIAL, VOLUME, STORE, SUPPLY_PRICE, INPRICE, DIFFERENCE)
AS
  SELECT T_MATERIAL.NAME, T_SUPPLY.VOLUME, T_STORE.NAME,V_SUPPLY_2.SUMM, V_INPRICE.SUMM, ABS(V_SUPPLY_2.SUMM - V_INPRICE.SUMM)
    FROM T_SUPPLY JOIN T_MATERIAL 
    ON T_SUPPLY.ID_MATERIAL = T_MATERIAL.ID_MATERIAL
    JOIN T_STORE 
    ON T_SUPPLY.ID_STORE = T_STORE.ID_STORE
    JOIN V_SUPPLY_2 
    ON T_SUPPLY.ID_SUPPLY = V_SUPPLY_2.ID
    JOIN V_INPRICE 
    ON T_SUPPLY.ID_SUPPLY = V_INPRICE.ID;